# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Michael Veale
email: m.veale@ucl.ac.uk
description: > # this means to ignore newlines until "url:"
  Academic website for Michael Veale
footer_text: >
  Thanks to <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> and the <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url: veale.github.io # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: veale
twitter_username: mikarv
linkedin_username: mveale
scholar_authorid: THA7V3IAAAAJ
contact_note: >
  Need a speedy response? Email and Twitter are your best bet.
# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Michael Veale
blog_description: too long for twitter, too short for a journal

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: mikarv # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes
include: ['_pages']

# Gems
gems:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Veale

  style: ./assets/bib/chicago-annotated-bibliography.csl
  locale: en

  sort_by: year, month, day
  order: descending

  source: /_bibliography/
  bibliography: personal_bibliography.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
